apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1040752571-deployment
  labels:
    app: soc-1040752571
spec:
  replicas: 2
  selector:
    matchLabels:
      app: soc-1040752571
  template:
    metadata:
      labels:
        app: soc-1040752571
    spec:
      containers:
      - name: soc-contenedor
        image: 047719650114.dkr.ecr.us-east-1.amazonaws.com/s1040752571:latest
        ports:
        - containerPort: 5000
